"""empty message

Revision ID: ca819edb56e3
Revises: adbb2b7b49a1
Create Date: 2023-05-17 11:46:34.473856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca819edb56e3'
down_revision = 'adbb2b7b49a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('cp')

    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.drop_column('cp')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cp', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cp', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
